apiVersion: v1
kind: Secret
metadata:
  name: contact-secrets
  namespace: contactmicroservices
  labels:
    app.kubernetes.io/name: contact-secrets
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: contact-system
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "Secrets para os microserviços de contatos"
type: Opaque
data:
  # RabbitMQ Password (base64 encoded: guest)
  RABBITMQ__PASSWORD: Z3Vlc3Q=
  
  # SQL Server Connection String (base64 encoded)
  # Server=sqlserver-service;Database=ContactsDB;User Id=sa;Password=ContactsDB@2024;TrustServerCertificate=true;
  CONNECTIONSTRINGS__DEFAULTCONNECTION: U2VydmVyPXNxbHNlcnZlci1zZXJ2aWNlO0RhdGFiYXNlPUNvbnRhY3RzREI7VXNlciBJZD1zYTtQYXNzd29yZD1Db250YWN0c0RCQDIwMjQ7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVlOw==

---
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secrets
  namespace: contact-microservices
  labels:
    app.kubernetes.io/name: sqlserver-secrets
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: database-secrets
    app.kubernetes.io/part-of: contact-system
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "Secrets do SQL Server"
type: Opaque
data:
  # SA Password (base64 encoded: ContactsDB@2024)
  SA_PASSWORD: Q29udGFjdHNEQkAyMDI0

