name: Fase 4 CI/CD
on: [push]

env:
  REGISTRY: docker.io
  IMAGE_NAME: zennbyte

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - service: ContactCreate.API
            service_slug: create-contact
          - service: ContactRead.API
            service_slug: read-contact
          - service: ContactUpdate.API
            service_slug: update-contact
          - service: ContactDelete.API
            service_slug: delete-contact
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login 
      uses: docker/login-action@v3.0.0
      with:
        username: 'zennbyte'
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/zennbyte/${{ matrix.service_slug }}
        tags: |
          latest
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
